//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeFiles
    {
        public System.Guid Id { get; set; }
        public string Path { get; set; }
        public string Content { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.Guid> Session_Id { get; set; }
    
        public virtual Sessions Sessions { get; set; }
    }
}
