//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PathNodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PathNodes()
        {
            this.PathNodeParameters = new HashSet<PathNodeParameters>();
        }
    
        public System.Guid Id { get; set; }
        public string Hash { get; set; }
        public string Namespace { get; set; }
        public string Type { get; set; }
        public string Method { get; set; }
        public string Parent { get; set; }
        public System.Guid Parent_Id { get; set; }
        public string Origin { get; set; }
        public string ReturnType { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.Guid> MethodCodeMetric_Id { get; set; }
        public Nullable<System.Guid> Session_Id { get; set; }
        public System.Guid Event_Id { get; set; }
    
        public virtual CodeMetrics CodeMetrics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PathNodeParameters> PathNodeParameters { get; set; }
        public virtual Sessions Sessions { get; set; }
    }
}
