//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sessions()
        {
            this.Breakpoints = new HashSet<Breakpoints>();
            this.CodeFiles = new HashSet<CodeFiles>();
            this.Events = new HashSet<Events>();
            this.PathNodes = new HashSet<PathNodes>();
        }
    
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public System.DateTime Started { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
        public string DeveloperName { get; set; }
        public string TaskName { get; set; }
        public string TaskAction { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<System.DateTime> TaskCreated { get; set; }
        public System.TimeSpan TaskTotalSessionTime { get; set; }
        public string ProjectName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Breakpoints> Breakpoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodeFiles> CodeFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Events> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PathNodes> PathNodes { get; set; }
    }
}
